POST http://localhost:3000/cadastro
Content-Type: application/json
{
    "name": "Victor Sarrís",
    "email": "devvictorsarris@gmail.com",
    "password": "123456789",
    "isAdmin": "admin"
}

POST: http://localhost:3000/login
Content-Type: application/json

{
    "email": "devvictorsarris@gmail.com",
    "password": "Sarris120705"
}

###

GET http://localhost:3000/cadastro
Authorization: token